// design-sync-entry.ts — entry cho design-sync (claude.ai/design), KHONG dung trong app.
// Re-export moi component default-export theo TEN de bundle IIFE co window.WuWaEcho.<Name>.
// Them component moi vao app/src/components/ => them 1 dong o day (validate se bao thieu neu quen).
export { default as AnchorToggle } from './components/AnchorToggle'
export { default as BenchPanel } from './components/BenchPanel'
export { default as BestOwnerBadge } from './components/BestOwnerBadge'
export { default as BuildCostEstimator } from './components/BuildCostEstimator'
export { default as BuildEditor } from './components/BuildEditor'
export { default as CharacterPicker } from './components/CharacterPicker'
export { default as CleanupPanel } from './components/CleanupPanel'
export { default as DeltaBadge } from './components/DeltaBadge'
export { default as EchoCard } from './components/EchoCard'
export { default as EchoEditModal } from './components/EchoEditModal'
export { default as EchoFields } from './components/EchoFields'
export { default as EchoForm } from './components/EchoForm'
export { default as EchoLine } from './components/EchoLine'
export { default as EmptyState } from './components/EmptyState'
export { default as ErrorBoundary } from './components/ErrorBoundary'
export { default as FarmingBacklog } from './components/FarmingBacklog'
export { default as InfoTip } from './components/InfoTip'
export { default as LoadoutView } from './components/LoadoutView'
export { default as MainEchoHint } from './components/MainEchoHint'
export { default as OcrImport } from './components/OcrImport'
export { default as PinnedByBadge } from './components/PinnedByBadge'
export { default as PinnedOverview } from './components/PinnedOverview'
export { default as RankingTable } from './components/RankingTable'
export { default as RosterPanel } from './components/RosterPanel'
export { default as ScannerImport } from './components/ScannerImport'
export { default as ScoreBadge } from './components/ScoreBadge'
export { default as SetFarmPriority } from './components/SetFarmPriority'
export { default as SetPicker } from './components/SetPicker'
export { default as Stale } from './components/Stale'
export { default as StatBreakdown } from './components/StatBreakdown'
export { default as SubstatLegend } from './components/SubstatLegend'
export { default as TriagePanel } from './components/TriagePanel'
export { default as UpgradePlanPanel } from './components/UpgradePlanPanel'
export { default as VaultBar } from './components/VaultBar'
export { default as WeightEditor } from './components/WeightEditor'
export { I18nProvider } from './i18n'
